language: node_js

cache:
  directories:
    - ~/.npm

node_js:
  - 8

jobs:
  include:
#    - stage: install
#      script: npm ci
#      skip_cleanup: true
    - stage: lint
      script: npm run check
      skip_cleanup: true
    - stage: test
      script: npm run test:prod
      skip_cleanup: true
    - stage: release
      node_js: lts/*
      script: skip     # usually you do not want to rerun any tests
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm run build
          - npx semantic-release
      if: branch = master
