language: node_js

cache:
  directories:
    - ~/.npm

node_js:
  - 8

jobs:
  include:
    - stage: install
      script: npm install
      skip_cleanup: true
    - stage: lint
      script: npm run check
      skip_cleanup: true
    - stage: test
      script: npm run test:prod
      skip_cleanup: true
    - stage: build
      script: npm run build
      skip_cleanup: true
    - stage: release
      node_js: lts/*
      # Advanced: optionally overwrite your default `script` step to skip the tests
      # script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
      if: branch = master
